[package]
name = "ntfy2clip"
version = "0.6.0"
edition = "2021"

[[bin]]
name = "n2c"
path = "src/client.rs"

[dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "net",
    "macros",
    "process",
    "time",
] }
log = "0.4"
pretty_env_logger = "0.5"
anyhow = "1"
tokio-tungstenite = { version = "*", features = ["native-tls"] }
url = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-util = "0.3"
